### ISSUE TITLE
Incorrect inertia for FER

### ISSUE THREAD

**Issue by Kotochleb** [frankaemika/franka_description#3]
When launching example from [franka_ros2](https://github.com/frankaemika/franka_ros2) with command
```bash
ros2 launch franka_gazebo_bringup gazebo_joint_impedance_controller_example.launch.py load_gripper:=true franka_hand:='franka_hand' arm_id:=fer
```
FER returns errors related to inertia and is not spawning the robot in Ignition Gazebo
```
[rviz2-3] [ERROR] [1720787708.413849623] [rviz2]: The link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.

...

[ruby $(which ign) gazebo-1] [Err] [UserCommands.cc:1138] Error Code 18: Msg: A link named fer_link4 has invalid inertia.
```

On a side note, FP3 and FR3 are fine. Copying inertia from other robots solves the problem.

**Comment by AndreasKuhner** [comment]
Hi Kotochleb,
thanks for the mention. Yes, that is known. But as you mention, using the ones from FX3 is just fine and fits for FER as well :)
