### ISSUE TITLE
Specify unique namespaces for robots in xacros?

### ISSUE THREAD

**Issue by shart-bdai** [frankaemika/franka_description#5]
From what I can tell, the current robot/hand xacros are not set up to support adding arbitrary namespaces to the links and joints.  Is this correct?

we are looking to build a dual-fr3 setup in which we have left and right arms in the same URDF, but from what I can tell this is not currently supported, and the changes would be pretty messy due to the the different setup cases (gazebo, ros2_control, different hands),  and the loaded yaml config files for the things like inertials, joint_limits, etc.  

would it be possible to request this, if not currently possible?

**Comment by shart-bdai** [comment]
Took a stab at what this might look like (though by no means fully tested).  
[namespace_prefix_diff.txt](https://github.com/user-attachments/files/16985611/namespace_prefix_diff.txt)


Any recs on how to do this better would be apprecaited.

**Comment by AndreasKuhner** [comment]
Hi shart-bdai, 
we are actually currently on it to enhance the URDFs/Xacros to support multi arm setups. This would also include handling the prefixes. But to be honest, we currently focus on getting it to run with ros2_control... so, for other use-cases, it might be a bit rough around the edges and might not yet fully work out-of-the-box with our current 5.6.0 image. 

A bit of background, we also need to enhance our backend, which means it will be included in an upcoming image release... most likely with 5.8.0 - but the goal here is that the user can do a multi arm setup via ros2_control (those **communication_constraint_violations** are spoiling the party a bit...)

All in all, we might also release the URDF changes earlier with the hint that it might not work stable. Maybe we just release it on a experimental branch for now... not yet decided :)
