### ISSUE TITLE
issue of the generation of franka panda urdf model using docker and franka_description on github

### ISSUE THREAD

**Issue by g-cc-c** [frankaemika/franka_description#6]
I tried to use the official discription files on github and docker to generate the urdf for fer (panda robot):
https://github.com/frankaemika/franka_description 

I met this error, as shown in the attached picture. Since I never used docker before, I do not know whether my writing format is wrong, or I have made other mistakes, which lead to this error. My aim is to generate the urdf for fer (panda), without end effector. I would like to know what is wrong, or how should I write in order to generate the corresponding urdf?
![4119b5d0c4dd769e0f71dc85764e7145c5722916](https://github.com/user-attachments/assets/5efa26da-333c-485a-8462-29722d3e98b7)

**Comment by AndreasKuhner** [comment]
Hey gordoncooongg,
thank you for reporting it. We noted it and will let you know when it is fixed :)

Cheers,
Andreas

**Comment by BarisYazici** [comment]
@gomezgu do you have any insights?

**Comment by gomezgu** [comment]
Hello gordoncooongg,

The error is in fer.urdf.xacro:

 ```
 <xacro:franka_robot arm_id="$(arg arm_id)"
                      joint_limits="${xacro.load_yaml('$(find franka_description)/robots/$(arg arm_id)/joint_limits.yaml')}"
                      inertials="${xacro.load_yaml('$(find franka_description)/robots/$(arg arm_id)/inertials.yaml')}"
                      kinematics="${xacro.load_yaml('$(find franka_description)/robots/$(arg arm_id)/kinematics.yaml')}"
                      dynamics="${xacro.load_yaml('$(find franka_description)/robots/$(arg arm_id)/dynamics.yaml')}"
                      gazebo="$(arg gazebo)"
                      hand="$(arg hand)"
                      ee_id="$(arg ee_id)"
                      with_sc="$(arg with_sc)"
                      ros2_control="$(arg ros2_control)"
                      robot_ip="$(arg robot_ip)"
                      use_fake_hardware="$(arg use_fake_hardware)"
                      fake_sensor_commands="$(arg fake_sensor_commands)"
                      gazebo_effort="$(arg gazebo_effort)">
  </xacro:franka_robot>
</robot>
```
**</xacro:franka_robot>**  is missing at the end.
We will push the fix in the coming days. In the meanwhile, you can add the line manually.

Best,
Guillermo
